// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsk.KeyRotation.EntityFramework;

#nullable disable

namespace Samples.KeyRotationWithEntityFramework.Migrations
{
    [DbContext(typeof(KeyRotationDbContext))]
    [Migration("20251124113030_KeyRotation_V1")]
    partial class KeyRotation_V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.SigningKeyEntity", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ActiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KetSetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KeyMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyId");

                    b.HasIndex("KetSetId");

                    b.ToTable("SigningKeys");
                });

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.SigningKeySetEntity", b =>
                {
                    b.Property<string>("KeySetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.HasKey("KeySetId");

                    b.ToTable("SigningKeySets");
                });

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.SigningKeyEntity", b =>
                {
                    b.HasOne("Rsk.KeyRotation.EntityFramework.Entities.SigningKeySetEntity", null)
                        .WithMany("SigningKeys")
                        .HasForeignKey("KetSetId");
                });

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.SigningKeySetEntity", b =>
                {
                    b.Navigation("SigningKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
