// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsk.KeyRotation.EntityFramework;

#nullable disable

namespace Samples.KeyRotationWithEntityFramework.Migrations
{
    [DbContext(typeof(KeyRotationDbContext))]
    partial class KeyRotationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.KeyEntity", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ActiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KeyMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeySetId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KeyId");

                    b.HasIndex("KeySetId");

                    b.ToTable("RskSecurityKeys");
                });

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.KeySetEntity", b =>
                {
                    b.Property<string>("KeySetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.HasKey("KeySetId");

                    b.ToTable("RskSecurityKeySets");
                });

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.KeyEntity", b =>
                {
                    b.HasOne("Rsk.KeyRotation.EntityFramework.Entities.KeySetEntity", null)
                        .WithMany("Keys")
                        .HasForeignKey("KeySetId");
                });

            modelBuilder.Entity("Rsk.KeyRotation.EntityFramework.Entities.KeySetEntity", b =>
                {
                    b.Navigation("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
